# Setup
title:               åŒ—ç“œæ‘
tagline:             'A Common MC server'
description:         'ç®€å•çš„MCæ­£ç‰ˆJAVAæœåŠ¡å™¨</br>
                      ä¸€ç¾¤çƒ­çˆ±åŸç‰ˆç”Ÿå­˜çš„ç©å®¶ğŸ•Š</br>
                      ä¸€ä¸ªå……å½“ğŸšªé¢çš„å®˜ç½‘ã€‚</br>
                      ä¸€åˆ‡åªä¸ºå¼€å¿ƒã€‚</br>
                      Good Luck and Have Funï¼ğŸ‡'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
